"""Initial migration - create products table

Revision ID: ff1e4baaaf00
Revises: 
Create Date: 2025-11-08 14:58:14.238191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1e4baaaf00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('orig_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Original price'),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Actual selling price'),
    sa.Column('platform', sa.String(length=100), nullable=False, comment='Platform where product was sold'),
    sa.Column('date_of_selling', sa.DateTime(timezone=True), nullable=False, comment='Date and time of sale'),
    sa.Column('country_of_selling', sa.String(length=100), nullable=False, comment='Country where sale occurred'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_country_of_selling'), 'products', ['country_of_selling'], unique=False)
    op.create_index(op.f('ix_products_date_of_selling'), 'products', ['date_of_selling'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_platform'), 'products', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_platform'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_date_of_selling'), table_name='products')
    op.drop_index(op.f('ix_products_country_of_selling'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
